import NextHead from 'next/head';

interface HeadProps {
  title: string;
}

function Head({ title }: HeadProps) {
  return (
    <NextHead>
      <title>{title}</title>

      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </NextHead>
  );
}

export default Head;
